@PocAddress = http://localhost:5224/api/poc

GET {{PocAddress}}/

###

POST {{PocAddress}}/
Content-Type: application/json

{
    "Name":"Kumar",
    "Role":"Lecturer",
    "Contact":8765456789,
    "Email":"kumar@gmail.com"
}

###

# 

PUT {{PocAddress}}/
Content-Type: application/json

{
    "id": 1,
    "name": "Sabari",
    "role": "Lecturer",
    "contact": 8765456789,
    "email": "ragu@gmail.com"
}

###

DELETE {{PocAddress}}/kumar@gmail.com